export enum SubjectConstants {
    USER = 'USER',
    SERVER = 'SERVER',
    ONLINE_SERVER = 'ONLINE_SERVER',
    ONLINE_PLAYER = 'ONLINE_PLAYER',
    ONLINE_CHAT = 'ONLINE_CHAT',
    KICK_REASON = 'KICK_REASON',
    CURRENT_USER = 'CURRENT_USER',
    BAN_REASON = 'BAN_REASON',
}